# Generated by Django 4.1.3 on 2022-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non_IT'), ('Mobile Phone', 'Mobile Phone')], max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
